### ISSUE TITLE
Force checkout refresh when add to cart clicked on checkout

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/edd-cross-sell-upsell#4]
When you display add to cart buttons on the checkout, and click them, the cart doesn't refresh. There is an attribute you can pass the purchase link function of `'direct' => true`, which will force a refresh of the checkout after adding the item from the checkout. This follows what Recommended Products is doing as well.

**Comment by sumobi** [comment]
The only issue with that is that after adding one of the upsells to the checkout, it takes me straight to Paypal, rather than refreshing the page.

**Comment by pippinsplugins** [comment]
You could force the button behavior to add to cart instead of buy now

**Comment by sumobi** [comment]
Bingo

**Comment by SDavisMedia** [comment]
@amdrew can you hit this in the near future? Someone's asking about it and I do think this should be standard in the plugin. Thanks.

**Comment by amdrew** [comment]
@SDavisMedia Will do my best to 👍

**Comment by amdrew** [comment]
@cklosowski @pippinsplugins @SDavisMedia PR: https://github.com/easydigitaldownloads/edd-cross-sell-upsell/pull/14

Setting `direct` to `true` works, but if the download has the `Purchase button behavior` set to `Buy Now`, and the download appears as a cross-sell at checkout, then clicking "Add to cart" takes the customer to PayPal for example, rather than refreshing the cart (as per https://github.com/easydigitaldownloads/edd-cross-sell-upsell/issues/4#issuecomment-231708056)

It seems the solution here is actually set `direct` to `false` which refreshes the cart in my testing for each cross-sell and also prevents a download going to PayPal if their purchase button behavior is set to "buy now".

If anyone agrees, I'll merge and push out an update!

**Comment by SDavisMedia** [comment]
@amdrew I'm not seeing how this is changing the original behavior.

Cross sells at checkout still work the same for me, adding them to the cart and having to manually refresh. I didn't test any further than that.

What does adding `'direct' => false` do to change that behavior and force a cart refresh?

**Comment by amdrew** [comment]
@SDavisMedia Thanks! It's not working for me now also. I think I was cached and somehow thought I found the garden of eden. Seeing some weird stuff now with downloads going to PayPal when they shouldn't. Will take a step back for a moment and regroup my troops.

**Comment by amdrew** [comment]
@SDavisMedia Ok, tracked it down.

It turns out that when Recommended Products is enabled (with Cross-sell/Upsell enabled), clicking "add to cart" on the downloads shown from Cross-sell/Upsell reload the checkout as intended. I thought this was due to my `'direct' => false` being adding to the purchase link. When Recommended products is disabled, the add to cart buttons do _not_ refresh the checkout. That is why @SDavisMedia sees the same behavior as before. Essentially, the PR does nothing (yet).

I also found that Recommended Products actually uses `'direct' => false` on its purchase links, not `true` as originally stated. With Recommended products active, the following is added by EDD to checkout's HTML source:

`<input type="hidden" name="edd_redirect_to_checkout" id="edd_redirect_to_checkout" value="1">`

That lead me to this filter being set to `true` in Recommended Products:
https://github.com/easydigitaldownloads/edd-recommended-products/blob/master/includes/template-functions.php#L77

So from what I can see, Recommended Products forces products to go straight to checkout, while on the checkout, hence the page reload. This is also why the add to cart links from Cross-sell/Upsell work when it's enabled.

So the fix here seems to be doing the same as recommended products. That is, we force the filter to true if on the checkout screen. I can't see/think of any conflicts at this point. If recommended products is doing it then we should be safe already.

The `'direct' => false` is still needed as per the original PR. This ensures that any download with the "buy now" behavior does not go straight to PayPal.

**Comment by amdrew** [comment]
@SDavisMedia Can you please pull down the latest commit and test again. Don't do it on your birthday though.

**Comment by SDavisMedia** [comment]
@amdrew Outstanding. Everything's working wonderfully, including using the Add to Cart button for a cross-sell at checkout when that product being added would go straight to PayPal if clicked from anywhere else. Looking great to me. :+1:

**Comment by amdrew** [comment]
@SDavisMedia Perfecto, I'll get a small release pushed out today!

**Comment by SDavisMedia** [comment]
Sweet deal!
